# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

###### CODEQL SCANNER START

    - name: CodeQL Bundle
      uses: advanced-security/codeql-bundle-action@v1.1.0
      #with:
        # A comma-separated list of CodeQL packs to include in the bundle
      #  packs: ''
          
###### CODEQL SCANNER END

###### TRIVY CODE SCANNER START

    #- name: Aqua Security Trivy
    #  uses: aquasecurity/trivy-action@0.28.0
      
    #- name: Upload Trivy Scan Result
    #  uses: github/codeql-action/upload-sarif@v3
    #  with:
    #    sarif_file: trivy-results1.sarif
    #- name: Aqua Build Security
  
    #  uses: aquasecurity/build-security-action@v0.0.1
    #  with:
    #    aqua_key: ''
    #    aqua_secret: ''
        
###### TRIVY CODE SCANNER END
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
